[package]
name = "example-rust-ado"
version = "0.1.0"
authors = ["Daniel Waddington <daniel.waddington@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
